luxteam/jobs_test_blender

- scripts/make_results_baseline.bat
- scripts/make_results_baseline.sh
- scripts/run.bat
- scripts/run.sh
Needed for correct work pipeline during of send to Report Builder System
> Update name of result dir for Blender2.8

- .gitmodules
- jobs/Scripts/simpleRender.py
Implement kill process from jobs_launcher
> Implement kill process from jobs_launcher

- jobs/Tests/Color_Managment/test_cases.json
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/919/Test_20Report/
> Unskipped Color_Managment group

- jobs/Tests/AOV/test.job-manifest.xml
- jobs/Tests/Adaptive_Sampling/test.job-manifest.xml
- jobs/Tests/Animation/test.job-manifest.xml
- jobs/Tests/Camera/test.job-manifest.xml
- jobs/Tests/Color_Managment/test.job-manifest.xml
- jobs/Tests/Denoiser/test.job-manifest.xml
- jobs/Tests/Hybrid/test.job-manifest.xml
- jobs/Tests/IBL/test.job-manifest.xml
- jobs/Tests/Image_Size/test.job-manifest.xml
- jobs/Tests/Material_Library/test.job-manifest.xml
- jobs/Tests/Physical_Lights/test.job-manifest.xml
- jobs/Tests/Pixel_Filter/test.job-manifest.xml
- jobs/Tests/Portal_Lights/test.job-manifest.xml
- jobs/Tests/Principled_BSDF/test.job-manifest.xml
- jobs/Tests/Quality/test.job-manifest.xml
- jobs/Tests/RPR_Nodes/test.job-manifest.xml
- jobs/Tests/Smoke/test.job-manifest.xml
- jobs/Tests/Uber/test.job-manifest.xml
- jobs/Tests/Volume/test.job-manifest.xml
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8Plugin-WeeklyFull/108/Test_20Report/
timeout = 2*time_taken
> timeout = 2*time_taken

- jobs/Scripts/base_functions.py
- jobs/Scripts/refactor_logs.py
- jobs/Scripts/simpleRender.py
640
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/968/
> Fix blender logging

- jobs/Tests/Denoiser/test_cases.json
- jobs/Tests/Physical_Lights/test_cases.json
Нужно обновить baseline BL28_RS_IBL_034 @Piromancer 
В physical lights поменялись названия параметров, пока не поправят можно скипать
> skip some cases

- jobs/Scripts/base_functions.py
- jobs/Scripts/refactor_logs.py
- jobs/Scripts/simpleRender.py
https://adc.luxoft.com/jira/browse/STVCIS-826
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/1038/
> Add retry for cases

- jobs/Scripts/base_functions.py
- JIRA TICKET:
https://adc.luxoft.com/jira/browse/STVCIS-854
- PURPOSE:
Fix 404 error on skipped cases logs
> fix skipped cases logs

- jobs/Tests/Cloud/test_cases.json
https://adc.luxoft.com/jira/browse/STVCIS-928
All cases were updated, fixed scenes were unskipped.
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/1264/Test_20Report/
Note: 020 is skipped
> Cloud unskipped

- jobs/Tests/Cloud/test_cases.json
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/1368/Test_20Report/
> Cloud 005 skipped on nvidia

- jobs/Tests/Smoke/test_cases.json
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/1387/Test_20Report/
Cases 043-046 added
ML on CPU mode (case 043) doesn't work, which is an issue (already reported it to QA)
> Cpu&gpu smoke

- jobs/Scripts/simpleRender.py
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-831
> Add log message

- jobs/Scripts/base_functions.py
- jobs/Scripts/simpleRender.py
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-936
* PURPOSE
* Retry case ones
* Rename fail_count (because it's errors count)
* Features already tested
> Change retries count and rename fail_count

- jobs/Tests/AOV/test.job-manifest.xml
- jobs/Tests/Adaptive_Sampling/test.job-manifest.xml
- jobs/Tests/Animation/test.job-manifest.xml
- jobs/Tests/Camera/test.job-manifest.xml
- jobs/Tests/Cloud/test.job-manifest.xml
- jobs/Tests/Color_Managment/test.job-manifest.xml
- jobs/Tests/Denoiser/test.job-manifest.xml
- jobs/Tests/Emissive_Light/test.job-manifest.xml
- jobs/Tests/Hybrid/test.job-manifest.xml
- jobs/Tests/IBL/test.job-manifest.xml
- jobs/Tests/IES/test.job-manifest.xml
- jobs/Tests/IES_Intensity/test.job-manifest.xml
- jobs/Tests/Image_Formats/test.job-manifest.xml
- jobs/Tests/Image_Size/test.job-manifest.xml
- jobs/Tests/Import_Export/test.job-manifest.xml
- jobs/Tests/Material_Library/test.job-manifest.xml
- jobs/Tests/Motion_Blur/test.job-manifest.xml
- jobs/Tests/Physical_Lights/test.job-manifest.xml
- jobs/Tests/Pixel_Filter/test.job-manifest.xml
- jobs/Tests/Portal_Lights/test.job-manifest.xml
- jobs/Tests/Principled_BSDF/test.job-manifest.xml
- jobs/Tests/Quality/test.job-manifest.xml
- jobs/Tests/RPR_Nodes/test.job-manifest.xml
- jobs/Tests/Render_Layer/test.job-manifest.xml
- jobs/Tests/Render_Stamp/test.job-manifest.xml
- jobs/Tests/Smoke/test.job-manifest.xml
- jobs/Tests/Sun_Sky/test.job-manifest.xml
- jobs/Tests/Uber/test.job-manifest.xml
- jobs/Tests/Volume/test.job-manifest.xml
- local_config.py
* JIRA TICKET:
* https://adc.luxoft.com/jira/browse/STVCIS-816
* PURPOSE
* Refactor structure of jobs launcher. Made possibility to run plugins, viewer, core and converter from one unique jobs_launcher branch.
* EFFECT OF CHANGE
* Remove buildReport.html script call.
* Add report_type param in local config.
* TECHNICAL STEPS
* Open any render job
* Specify inemankov/refactor_jobs_launcher branch in 'test branch' field (code in this branch contains local_config with attribute which are necessary to build report).
* Run render job
* None
* REPORTS
* Blender: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/1569/Test_20Report/
* Core: https://rpr.cis.luxoft.com/job/RadeonProRenderCoreManual/440/Test_20Report/
> [CIS Refactor] Refactor jobs_launcher

- scripts/run.bat
- scripts/run.sh
* PURPOSE
* Fix default values on run.* scripts
* Northstar don't work on mac and ubuntu with R7
* REPORTS
* https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/1648/Test_20Report/
* https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/1649/Test_20Report/
> Fix default values of engine

- scripts/build_rpr_cache.bat
- scripts/build_rpr_cache.sh
- scripts/run.bat
- scripts/run.sh
Reverts luxteam/jobs_test_blender#59
> Revert "Put blender assets to gitlab"

- jobs/Scripts/extensions/NorthStar.py
- jobs/Tests/NorthStar/test_cases.json
- jobs/Tests/Smoke/test_cases.json
- PURPOSE
For the same reasons as there:
https://github.com/luxteam/jobs_test_blender/pull/71
AOV related test cases should be fixed.
> Fix AOV test cases

- jobs/Tests/Cloud/test_cases.json
- jobs/Tests/Hybrid/test_cases.json
> Cloud Hybrid skips

- jobs/Tests/Sun_Sky/test_cases.json
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginAuto/job/develop/36/Test_20Report/AMD_WX7100-Windows/Results/Blender28/Sun_Sky/report.html
Due to this issue
> Fixed regression

- jobs/Tests/Denoiser/test_cases.json
> Skipped ml on ubuntu

- jobs/Scripts/base_functions.py
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-1296
* PURPOSE
* Fix issue with enabling rpr in cases that load scene inside case functions
> Replace enable rpr

- scripts/run.bat
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-1332
> Fix engine feature

- jobs/Scripts/simpleRender.py
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-1281
* PURPOSE
* Optimize simple render for RPR_Nodes passing
* Using extended_blender_timeout pipeline branch to guarantee group finishing
* REPORTS
* https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2080/
> Optimize sync_time

- jobs/Scripts/base_functions.py
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-1293
* PURPOSE
* Fix issues with setup time
* Blender python context give different time on ubuntu, so I use utcnow
* REPORTS
> Fix setup time

- jobs/Tests/NorthStar/test_cases.json
NorthStar was implemented on all platforms
> Unskipped NorthStar on all platforms

- jobs/Scripts/simpleRender.py
- jobs/Tests/Athena/test_cases.json
- jobs/Tests/Cloud/test_cases.json
- jobs/Tests/Denoiser/test_cases.json
- jobs/Tests/Hybrid/test_cases.json
- jobs/Tests/NorthStar/test_cases.json
- jobs/Tests/Smoke/test_cases.json
- jobs/Tests/VDB/test_cases.json
- scripts/run.bat
* https://adc.luxoft.com/jira/browse/STVCIS-1389
* https://github.com/luxteam/jobs_test_maya/pull/164
* https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2695/
* https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2696/
> Add skip engine feature

- jobs/Tests/AOV/test_cases.json
- jobs/Tests/Color_Managment/test_cases.json
- jobs/Tests/Physical_Lights/test_cases.json
- jobs/Tests/Quality/test_cases.json
> Black image marks

- jobs/Scripts/simpleRender.py
https://adc.luxoft.com/jira/browse/STVCIS-1530
https://github.com/luxteam/jobs_test_maya/pull/170
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2727/
> Fix sync time issue

- jobs/Scripts/simpleRender.py
Reverts luxteam/jobs_test_blender#118
> Revert "Fix sync time issue"

- jobs/Scripts/simpleRender.py
* https://adc.luxoft.com/jira/browse/STVCIS-1469
* Make it possible to run builds with multiple engines
* Set path to baselines in case of Hybrid
* rpr_pipelines: https://github.com/luxteam/rpr_pipelines/pull/286
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/82
* jobs_test_maya: https://github.com/luxteam/jobs_test_maya/pull/167
> Make it possible to run builds with multiple engines

- jobs/Scripts/simpleRender.py
* None
* Set "passed" image as a rendered image for Athena
* https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2761/Test_20Report/
> Fix Athena

- jobs/Full-Hybrid
- jobs/Tests/AOV/test_cases.json
- jobs/Tests/Adaptive_Sampling/test.job-manifest.xml
- jobs/Tests/Cloud/test_cases.json
- jobs/Tests/Emissive_Light/test_cases.json
- jobs/Tests/IBL/test_cases.json
- jobs/Tests/Image_Size/test_cases.json
- jobs/Tests/Quality/test_cases.json
- jobs/Tests/RPR_Nodes/test_cases.json
- jobs/Tests/Smoke/test_cases.json
- PURPOSE
Skip known hybrid issues
> Hybrid skips

- jobs/Tests/Smoke/test.job-manifest.xml
Group doesn't pass due to timeout due to new cases
> New scenes timeout increased

- jobs/Scripts/base_functions.py
Replaced debug log due to spam in logs
> Debug replaced with info log

- jobs/Tests/Animation/test_cases.json
- jobs/regression.json
Changed cases, because changes between frames were unclear
> Animation cases changed

- jobs/Scripts/simpleRender.py
* https://adc.luxoft.com/jira/browse/STVCIS-1596
* Fix code in master
* Parse tool path for get Blender version
* Blender: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2828/
* Ubuntu&OSX: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2829/
> Fix code in master

- jobs/Tests/CPU_Mode/test_cases.json
Skipped CPU mode on NorthStar due to extremely low perf in Blender
> Skipped CPU on NorthStar engine

- scripts/build_rpr_cache.sh
* https://adc.luxoft.com/jira/browse/STVCIS-1709
* Fix cache building on Unix
* https://rpr.cis.luxoft.com/job/DevRadeonProRenderBlender2.8PluginManual/339/
> Fix cache building on Unix

- jobs/Tests/AOV/test_cases.json
> Skipped aov 015

- jobs/Tests/Athena/test_cases.json
> Deleted exessive tests for athena group

- jobs/Scripts/simpleRender.py
* https://adc.luxoft.com/jira/browse/STVCIS-1709
* Delete excess code
* https://rpr.cis.luxoft.com/job/DevRadeonProRenderBlender2.8PluginManual/430/
> Fix simpleRender script

- jobs/Tests/Physical_Lights/test.job-manifest.xml
- jobs/Tests/Physical_Lights/test_cases.json
Returned missing phys lights cases
> Returned missing cases

- jobs/Tests/Smoke/test_cases.json
> Skipped 044 smoke

- jobs/Tests/Cloud/test_cases.json
Skipped due to blender hanging on this case
> Skipped 028 on linux

- jobs/Tests/Animation/test_cases.json
Purpose:
To skip keyed animation
> skipped keyed_animation

- jobs/Tests/Cloud/test_cases.json
> Cloud 009 skipped on ubuntu

- jobs/Tests/Cloud/test_cases.json
> Skipped 028 cloud on mac

- jobs/Tests/Cloud/test_cases.json
> Cloud 028 skipped on ubuntu

- jobs/Tests/AOV/test_cases.json
> Skipped AOVs on Mac

- jobs/Scripts/simpleRender.py
* https://adc.luxoft.com/jira/browse/STVCIS-1842
* Fix creation of thumbnails for skipped cases
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/121
* jobs_test_maya: https://github.com/luxteam/jobs_test_maya/pull/228
* Blender: https://rpr.cis.luxoft.com/job/DevRadeonProRenderBlender2.8PluginManual/510/Test_20Report/
> Fix creation of thumbnails for skipped cases

- jobs/Scripts/refactor_logs.py
* https://adc.luxoft.com/jira/browse/STVCIS-1738
* Save additional performance json for each suite for UMS
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/110
* jobs_test_maya: https://github.com/luxteam/jobs_test_maya/pull/212
* Blender: https://rpr.cis.luxoft.com/job/DevRadeonProRenderBlender2.8PluginManual/428/
> [RBS] Performance tab (Jenkins Pipelines)

- jobs/Scripts/base_functions.py
- jobs/Scripts/makeReport.py
- jobs/Scripts/refactor_logs.py
- jobs/Scripts/simpleRender.py
* https://adc.luxoft.com/jira/browse/STVCIS-1890
* Make saving of test resutls of case more stable
* jobs_test_maya: https://github.com/luxteam/jobs_test_maya/pull/231
* https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3110/Test_20Report/
> Make saving of test resutls of case more stable

- jobs/Tests/Color_Managment/test.job-manifest.xml
- jobs/Tests/Motion_Blur/test.job-manifest.xml
- jobs/Tests/Physical_Lights/test.job-manifest.xml
- jobs/Tests/Render_Layer/test.job-manifest.xml
> Timeouts increased

- jobs/Scripts/simpleRender.py
* https://adc.luxoft.com/jira/browse/STVCIS-1713
* Do not recreate json files for error test cases
* jobs_test_maya: https://github.com/luxteam/jobs_test_maya/pull/268
> Do not recreate json files for error test cases

- jobs/Scripts/simpleRender.py
* https://adc.luxoft.com/jira/browse/STVCIS-1713
* Fix condition for stubs generation
* jobs_test_maya: https://github.com/luxteam/jobs_test_maya/pull/269
> Fix condition for stubs generation

- jobs/Tests/Particles/test.job-manifest.xml
> Fixed XML for particles

- jobs/Tests/Compositor/test_cases.json
- jobs/Tests/Dual_Mode/test_cases.json
Skipped dual on nvidia due to square artifacts
Skipped compositor 023 on mac due to https://amdrender.atlassian.net/browse/RPRBLND-1616
> Skipped dual mode and compositor on some gpus

- jobs/Full-NorthStar.json
> Add image node group to full

- jobs/Tests/IBL/test_cases.json
- PURPOSE
Add tests for IBL rotation settings
- REPORTS
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/3608/Test_20Report/
> IBL Rotation

- jobs/Scripts/base_functions.py
* https://adc.luxoft.com/jira/browse/STVCIS-2070
* Fix RETRIES = 1
> Fix RETRIES = 1

- jobs/Tests/Animation/test_cases.json
- jobs/Tests/Cloud/test_cases.json
- jobs/Tests/Denoiser/test.job-manifest.xml
- jobs/Tests/Denoiser/test_cases.json
- jobs/Tests/Smoke/test_cases.json
- PUROPOSE
Cover non F-16 denoiser with autotests
Unskip and skip some transparent BG scenes
Unskip fixed keyed animation
- REPORTS
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/3817/
> Denoiser, transparent bg

- jobs/Tests/CPU_Mode/test.job-manifest.xml
- jobs/Tests/Camera/test.job-manifest.xml
- jobs/Tests/Hair_BSDF/test.job-manifest.xml
> Increased timeouts for tahoe

- jobs/Tests/Cloud/test_cases.json
> Skip grease on 6800

- jobs/Tests/AOV/test_cases.json
> Skipped crypto on tahoe

- jobs/Tests/AOV/test_cases.json
Skipped due to https://amdrender.atlassian.net/browse/RPRBLND-1679
> Skip AO on ubuntu

- jobs/Tests/Cloud/test_cases.json
Skipped due to https://amdrender.atlassian.net/browse/RPRBLND-1655
> Skip grease pencil

- jobs/Tests/Cloud/test_cases.json
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4251/
> Skip BL28_BCS_041 case

- jobs/Tests/Cloud/test_cases.json
https://amdrender.atlassian.net/browse/RPRBLND-1690
> Skipped cloud 041

- jobs/Scripts/extensions/Motion_Blur.py
- jobs/Tests/Motion_Blur/test.job-manifest.xml
- jobs/Tests/Motion_Blur/test_cases.json
Purpose
- add new cases for Motion Blur for Blender
Jira Ticket
- https://adc.luxoft.com/jira/browse/STVQA-116
Jenkins Builds
- https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/4596/Test_20Report_20Northstar/
- https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/4596/Test_20Report_20Tahoe/
> New motion blur
